version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/node-pushserver
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/node-pushserver
          paths:
            - ./
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: npm run test
  build-docker:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/node-pushserver
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run:
          name: Docker build and push
          command: |
              docker build -t prodest/node-pushserver:$CIRCLE_TAG .
              docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
              docker push prodest/node-pushserver:$CIRCLE_TAG
  publish-rancher:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/node-pushserver
    steps:
      - attach_workspace:
          at: ./
      - run: ./scripts/deploy.sh api pushserver node-pushserver
workflows:
  version: 2
  build-with-context:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build-docker:
          context: Prodest
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}/ # v1.2.3
      - publish-rancher:
          context: Prodest
          requires:
            - build-docker
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}/ # v1.2.3